// Hardcoded demo scan — "AcmePay, Inc." — used by GET /api/demo so prospects
// can see a complete report before connecting AWS.

import type { ScanResults } from './types';

export function demoScan(): { id: string; org_name: string; results: ScanResults; created_at: number; completed_at: number; evidence_count: number } {
  const created = Date.now() - 1000 * 60 * 12;
  const completed = created + 1000 * 60 * 7;
  const results: ScanResults = {
    executive_summary:
      'AcmePay, Inc. scanned 12 SOC 2 controls. 5 pass, 4 partial, 2 fail, 1 inconclusive. Overall readiness: Near-ready. Average gap score 64/100, freshness 92/100. Critical work: enforce MFA on all IAM users, enable GuardDuty in eu-west-1, and configure RDS automated backups for `acmepay-prod-billing`.',
    overall_readiness: 'Near-ready',
    overall_gap_score: 64,
    overall_freshness_score: 92,
    critical_actions: [
      '[CC6.1] 3 IAM users without MFA — Enforce MFA via permission boundary policy',
      '[CC7.4] GuardDuty disabled in eu-west-1 — Enable GuardDuty across all active regions',
      '[CC9.2] acmepay-prod-billing RDS instance has 0-day backup retention — Set to ≥7 days',
      '[CC6.6] 2 S3 buckets allow public read — Apply bucket-level public access block',
      '[CC8.1] CloudTrail multi-region trail not enabled in 1 region — Enable management+data events',
    ],
    strengths: [
      'CC6.7: Restricted Data Movement & Encryption',
      'CC7.1: Configuration & Vulnerability Management',
      'CC7.2: Security Event Monitoring',
      'CC6.3: Role-Based Access & Segregation of Duties',
      'CC8.1: Change Management',
    ],
    evidence: [
      { id: 'ev_demo_1', service: 'iam', region: 'global', api: 'GetAccountSummary', timestamp: created, raw: '<GetAccountSummaryResponse><AccountMFAEnabled>1</AccountMFAEnabled><Users>14</Users><MFADevices>11</MFADevices></GetAccountSummaryResponse>', rawBytes: 412, truncated: false, severity: 'HIGH', controls: ['CC6.1', 'CC6.2'], summary: '3 of 14 IAM users without MFA' },
      { id: 'ev_demo_2', service: 'guardduty', region: 'us-east-1', api: 'GetDetector', timestamp: created, raw: '{"Status":"ENABLED","FindingPublishingFrequency":"FIFTEEN_MINUTES","DataSources":{"CloudTrail":{"Status":"ENABLED"},"S3Logs":{"Status":"ENABLED"},"Kubernetes":{"AuditLogs":{"Status":"ENABLED"}}}}', rawBytes: 234, truncated: false, severity: 'INFO', controls: ['CC7.4', 'CC7.3'], summary: 'GuardDuty enabled with full coverage' },
      { id: 'ev_demo_3', service: 'guardduty', region: 'eu-west-1', api: 'ListDetectors', timestamp: created, raw: '{"DetectorIds":[]}', rawBytes: 18, truncated: false, severity: 'HIGH', controls: ['CC7.4'], summary: 'No GuardDuty detector in eu-west-1' },
      { id: 'ev_demo_4', service: 'rds', region: 'us-east-1', api: 'DescribeDBInstances', timestamp: created, raw: '<DBInstances><DBInstance><DBInstanceIdentifier>acmepay-prod-billing</DBInstanceIdentifier><BackupRetentionPeriod>0</BackupRetentionPeriod><MultiAZ>false</MultiAZ></DBInstance></DBInstances>', rawBytes: 568, truncated: false, severity: 'CRITICAL', controls: ['CC9.2', 'CC6.7'], summary: 'acmepay-prod-billing has 0-day backups' },
      { id: 'ev_demo_5', service: 's3', region: 'global', api: 'GetPublicAccessBlock', timestamp: created, raw: '{"Buckets":["acmepay-public-assets","acmepay-marketing-2024"], "PublicReadAllowed":true}', rawBytes: 96, truncated: false, severity: 'HIGH', controls: ['CC6.6'], summary: '2 buckets allow public read' },
      { id: 'ev_demo_6', service: 'config', region: 'us-east-1', api: 'DescribeConfigurationRecorderStatus', timestamp: created, raw: '{"ConfigurationRecordersStatus":[{"name":"default","isEnabled":true}]}', rawBytes: 89, truncated: false, severity: 'INFO', controls: ['CC5.2', 'CC7.1'], summary: 'AWS Config enabled in us-east-1' },
      { id: 'ev_demo_7', service: 'config', region: 'eu-west-1', api: 'DescribeConfigurationRecorderStatus', timestamp: created, raw: '{"ConfigurationRecordersStatus":[]}', rawBytes: 32, truncated: false, severity: 'MEDIUM', controls: ['CC5.2'], summary: 'AWS Config not enabled in eu-west-1' },
      { id: 'ev_demo_8', service: 'securityhub', region: 'us-east-1', api: 'GetFindings', timestamp: created, raw: '{"Findings":[{"Id":"arn:aws:securityhub:us-east-1:743820195634:subscription/cis-aws-foundations-benchmark/v/1.2.0/1.5/finding/123","Severity":{"Label":"HIGH"},"RecordState":"ACTIVE"}]}', rawBytes: 456, truncated: false, severity: 'HIGH', controls: ['CC7.4'], summary: '7 active HIGH SecurityHub findings' },
      { id: 'ev_demo_9', service: 'cloudtrail', region: 'us-east-1', api: 'DescribeTrails', timestamp: created, raw: '{"trailList":[{"Name":"acmepay-org-trail","IsMultiRegionTrail":true,"IncludeGlobalServiceEvents":true,"IsOrganizationTrail":true}]}', rawBytes: 234, truncated: false, severity: 'INFO', controls: ['CC7.2', 'CC8.1'], summary: 'Multi-region CloudTrail enabled' },
      { id: 'ev_demo_10', service: 'kms', region: 'us-east-1', api: 'ListKeys', timestamp: created, raw: '{"Keys":[{"KeyId":"arn:aws:kms:us-east-1:743820195634:key/12345678-1234-1234-1234-123456789012","KeyState":"Enabled","KeyUsage":"ENCRYPT_DECRYPT"}]}', rawBytes: 198, truncated: false, severity: 'INFO', controls: ['CC6.7'], summary: 'KMS keys with rotation enabled' },
      { id: 'ev_demo_11', service: 'ec2', region: 'us-east-1', api: 'DescribeSecurityGroups', timestamp: created, raw: '{"SecurityGroups":[{"GroupId":"sg-12345","IpPermissions":[{"IpProtocol":"tcp","FromPort":22,"ToPort":22,"IpRanges":[{"CidrIp":"0.0.0.0/0"}]}]}]}', rawBytes: 145, truncated: false, severity: 'HIGH', controls: ['CC6.6'], summary: 'Security group allows SSH from anywhere' },
      { id: 'ev_demo_12', service: 'vpc', region: 'us-east-1', api: 'DescribeVpcs', timestamp: created, raw: '{"Vpcs":[{"VpcId":"vpc-12345","IsDefault":false}]}', rawBytes: 67, truncated: false, severity: 'INFO', controls: ['CC6.6'], summary: 'VPC configuration' },
      { id: 'ev_demo_13', service: 'lambda', region: 'us-east-1', api: 'ListFunctions', timestamp: created, raw: '{"Functions":[{"FunctionName":"acmepay-processor","Runtime":"nodejs18.x","LastModified":"2024-01-01T00:00:00Z"}]}', rawBytes: 123, truncated: false, severity: 'INFO', controls: ['CC8.1'], summary: 'Lambda functions tagged with version' },
      { id: 'ev_demo_14', service: 'waf', region: 'global', api: 'ListWebACLs', timestamp: created, raw: '{"WebACLs":[{"WebACLId":"waf-123","Name":"acmepay-waf"}]}', rawBytes: 89, truncated: false, severity: 'INFO', controls: ['CC6.6'], summary: 'WAF protects ALBs' },
      { id: 'ev_demo_15', service: 'cloudwatch', region: 'us-east-1', api: 'DescribeAlarms', timestamp: created, raw: '{"MetricAlarms":[{"AlarmName":"BillingAlarm","StateValue":"OK"}]}', rawBytes: 156, truncated: false, severity: 'INFO', controls: ['CC7.3'], summary: 'CloudWatch alarms for billing' },
      { id: 'ev_demo_16', service: 'sns', region: 'us-east-1', api: 'ListTopics', timestamp: created, raw: '{"Topics":[{"TopicArn":"arn:aws:sns:us-east-1:743820195634:acmepay-alerts"}]}', rawBytes: 98, truncated: false, severity: 'INFO', controls: ['CC7.3'], summary: 'SNS notifications to PagerDuty' },
      { id: 'ev_demo_17', service: 'alb', region: 'us-east-1', api: 'DescribeLoadBalancers', timestamp: created, raw: '{"LoadBalancers":[{"LoadBalancerArn":"arn:aws:elasticloadbalancing:us-east-1:743820195634:loadbalancer/app/acmepay-alb/123","Scheme":"internet-facing"}]}', rawBytes: 234, truncated: false, severity: 'INFO', controls: ['CC6.6'], summary: 'ALB configuration' },
      { id: 'ev_demo_18', service: 'organizations', region: 'global', api: 'DescribeOrganization', timestamp: created, raw: '{"Organization":{"Id":"o-12345","MasterAccountId":"743820195634"}}', rawBytes: 87, truncated: false, severity: 'INFO', controls: ['CC6.3'], summary: 'AWS Organization setup' },
      { id: 'ev_demo_19', service: 'sso', region: 'global', api: 'ListInstances', timestamp: created, raw: '{"Instances":[{"InstanceArn":"arn:aws:sso:::instance/ssoins-123"}]}', rawBytes: 76, truncated: false, severity: 'INFO', controls: ['CC6.1'], summary: 'AWS SSO enabled' },
      { id: 'ev_demo_20', service: 'backup', region: 'us-east-1', api: 'ListBackupVaults', timestamp: created, raw: '{"BackupVaultList":[{"BackupVaultName":"default"}]}', rawBytes: 54, truncated: false, severity: 'INFO', controls: ['CC9.2'], summary: 'AWS Backup vaults' },
      { id: 'ev_demo_21', service: 'route53', region: 'global', api: 'ListHostedZones', timestamp: created, raw: '{"HostedZones":[{"Id":"/hostedzone/Z12345","Name":"acmepay.com"}]}', rawBytes: 89, truncated: false, severity: 'INFO', controls: ['CC6.6'], summary: 'Route53 hosted zones' },
      { id: 'ev_demo_22', service: 'cloudformation', region: 'us-east-1', api: 'ListStacks', timestamp: created, raw: '{"StackSummaries":[{"StackName":"acmepay-infra","StackStatus":"CREATE_COMPLETE"}]}', rawBytes: 112, truncated: false, severity: 'INFO', controls: ['CC8.1'], summary: 'CloudFormation stacks' },
      { id: 'ev_demo_23', service: 'support', region: 'global', api: 'DescribeTrustedAdvisorChecks', timestamp: created, raw: '{"checks":[{"id":"123","name":"Security Groups - Specific Ports Unrestricted"}]}', rawBytes: 145, truncated: false, severity: 'HIGH', controls: ['CC6.6'], summary: 'Trusted Advisor checks' },
      { id: 'ev_demo_24', service: 'resource-groups', region: 'global', api: 'ListGroups', timestamp: created, raw: '{"Groups":[{"GroupArn":"arn:aws:resource-groups:us-east-1:743820195634:group/acmepay-resources"}]}', rawBytes: 123, truncated: false, severity: 'INFO', controls: ['CC5.2'], summary: 'Resource Groups' },
      { id: 'ev_demo_25', service: 'xray', region: 'us-east-1', api: 'GetSamplingRules', timestamp: created, raw: '{"SamplingRuleRecords":[{"SamplingRule":{"RuleName":"default","ResourceARN":"*","Priority":10000}]}', rawBytes: 167, truncated: false, severity: 'INFO', controls: ['CC7.2'], summary: 'X-Ray tracing' },
    ],
    controls: [
      { control_id: 'CC5.2', name: 'Technology Controls (Selection & Development)', status: 'partial', gap_score: 70, freshness_score: 95, summary: 'AWS Config rules enabled in 4/6 regions; SecurityHub standards (CIS, AWS Foundational) enabled. Process-level technology selection is outside technical scope.', findings: [], evidence_ids: ['ev_demo_6', 'ev_demo_7', 'ev_demo_24'], recommendations: ['Enable Config rules in eu-west-1 and ap-northeast-1.', 'Implement automated compliance monitoring.', 'Document technology selection criteria.', 'Regular security assessments of new tools.'], auditor_questions: ['What criteria are used for selecting cloud technologies?', 'How are security requirements integrated into technology selection?', 'Show evidence of vendor risk assessments.', 'Describe the process for evaluating new AWS services.'], partially_assessable: true, disclaimers: ['Process-level control selection out of technical scope.'], analyzed_at: completed },
      { control_id: 'CC6.1', name: 'Logical Access — Restricted Access', status: 'partial', gap_score: 58, freshness_score: 100, audit_risk: 'HIGH', summary: '3 of 14 IAM users have no MFA enabled. Password policy meets minimum requirements. KMS keys have rotation enabled.', findings: [{ id: 'f1', severity: 'HIGH', title: '3 IAM users without MFA', description: 'Users alice@acmepay.com, dev1@acmepay.com, contractor-bob have no MFA device registered. Per CC6.1 and CIS AWS 1.5, all IAM users with console access must have MFA.', evidence_id: 'ev_demo_1', remediation: 'aws iam enable-mfa-device --user-name alice --serial-number arn:aws:iam::743820195634:mfa/alice --authentication-code-1 123456 --authentication-code-2 789012' }], evidence_ids: ['ev_demo_1', 'ev_demo_19'], recommendations: ['Enforce MFA via SCP at the org level for all human IAM principals.', 'Migrate the three offending users to AWS SSO/Identity Center with enforced MFA.', 'Implement automated MFA compliance checks.', 'Set up MFA for all privileged accounts.'], auditor_questions: ['Show evidence that all IAM users with console access have MFA enrolled.', 'Walk through how a new employee gets IAM access — including approval, provisioning, and MFA enforcement.', 'What controls prevent MFA bypass?', 'How is MFA loss handled for emergency access?'], analyzed_at: completed },
      { control_id: 'CC6.2', name: 'System Access Provisioning', status: 'inconclusive', gap_score: 50, freshness_score: 80, summary: 'AWS shows IAM/SSO user creation timestamps but cannot validate provisioning approval workflow.', findings: [], evidence_ids: ['ev_demo_1', 'ev_demo_19'], recommendations: ['Provide HRIS-to-IAM provisioning runbook to your auditor.', 'Implement automated user lifecycle management.', 'Document access request and approval processes.', 'Set up regular access reviews.'], auditor_questions: ['Describe the user provisioning process from hire to access.', 'How are access rights reviewed and approved?', 'What happens when an employee leaves?', 'Show evidence of access provisioning controls.'], partially_assessable: true, disclaimers: ['Approval workflow out of technical scope.'], analyzed_at: completed },
      { control_id: 'CC6.3', name: 'Role-Based Access & Segregation of Duties', status: 'pass', gap_score: 88, freshness_score: 100, summary: 'IAM roles use least-privilege policies; SSO permission sets segregate duties; no wildcard admin grants outside break-glass role.', findings: [], evidence_ids: ['ev_demo_18'], recommendations: ['Continue regular policy reviews.', 'Implement automated policy analysis.', 'Document role definitions and responsibilities.'], auditor_questions: ['How are roles defined and assigned?', 'What segregation of duties controls exist?', 'Show examples of least-privilege policies.', 'Describe the break-glass access process.'], analyzed_at: completed },
      { control_id: 'CC6.6', name: 'External Threat Boundary', status: 'fail', gap_score: 42, freshness_score: 100, audit_risk: 'HIGH', summary: '2 S3 buckets allow public read access. WAF protects 3 of 4 ALBs. Security group allows SSH from anywhere.', findings: [{ id: 'f2', severity: 'HIGH', title: '2 S3 buckets allow public read', description: 'acmepay-public-assets and acmepay-marketing-2024 are missing PublicAccessBlock and have permissive bucket policies. Auditors will flag this against CC6.6 and CIS 2.1.5.', evidence_id: 'ev_demo_5', remediation: 'aws s3api put-public-access-block --bucket acmepay-public-assets --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true' }, { id: 'f5', severity: 'HIGH', title: 'SSH open to world', description: 'Security group sg-12345 allows SSH (port 22) from 0.0.0.0/0.', evidence_id: 'ev_demo_11', remediation: 'aws ec2 revoke-security-group-ingress --group-id sg-12345 --protocol tcp --port 22 --cidr 0.0.0.0/0' }], evidence_ids: ['ev_demo_5', 'ev_demo_11', 'ev_demo_14', 'ev_demo_17'], recommendations: ['Apply org-wide S3 BlockPublicAccess via SCP.', 'Add the fourth ALB to WAF coverage.', 'Restrict SSH access to specific IP ranges.', 'Implement network segmentation.'], auditor_questions: ['What controls prevent public S3 buckets from being created?', 'Provide CloudTrail evidence for the last 90 days of any public-bucket policy changes.', 'How is external access controlled?', 'Describe perimeter security measures.'], analyzed_at: completed },
      { control_id: 'CC6.7', name: 'Restricted Data Movement & Encryption', status: 'pass', gap_score: 90, freshness_score: 100, summary: 'All RDS instances encrypted at rest with customer-managed KMS keys. S3 default encryption enabled on all buckets. TLS 1.2+ enforced on ALBs.', findings: [], evidence_ids: ['ev_demo_4', 'ev_demo_10'], recommendations: ['Monitor encryption compliance.', 'Implement data classification policies.', 'Regular encryption key rotation.'], auditor_questions: ['How is data encryption enforced?', 'What encryption standards are used?', 'Describe data movement controls.', 'Show evidence of encryption key management.'], analyzed_at: completed },
      { control_id: 'CC7.1', name: 'Configuration & Vulnerability Management', status: 'pass', gap_score: 84, freshness_score: 100, summary: 'AWS Config tracking 142 resources. SecurityHub CIS standard at 86% pass rate.', findings: [], evidence_ids: ['ev_demo_6'], recommendations: ['Expand Config coverage to all regions.', 'Implement automated remediation.', 'Regular vulnerability scanning.'], auditor_questions: ['What configuration management tools are used?', 'How are vulnerabilities tracked and remediated?', 'Describe change management for configurations.', 'Show evidence of configuration compliance.'], analyzed_at: completed },
      { control_id: 'CC7.2', name: 'Security Event Monitoring', status: 'pass', gap_score: 86, freshness_score: 100, summary: 'CloudTrail multi-region trail with management + data events; CloudWatch metric filters and alarms in place.', findings: [], evidence_ids: ['ev_demo_9', 'ev_demo_25'], recommendations: ['Enable data event logging for S3.', 'Implement centralized logging.', 'Set up automated alerting.'], auditor_questions: ['What security events are monitored?', 'How are logs collected and analyzed?', 'Describe incident detection capabilities.', 'Show examples of security monitoring.'], analyzed_at: completed },
      { control_id: 'CC7.3', name: 'Anomaly Detection', status: 'partial', gap_score: 72, freshness_score: 100, summary: 'CloudWatch alarms cover billing + EC2 health; GuardDuty enabled in 5 of 6 regions. SNS notifications routed to PagerDuty.', findings: [], evidence_ids: ['ev_demo_2', 'ev_demo_3', 'ev_demo_15', 'ev_demo_16'], recommendations: ['Add GuardDuty in eu-west-1.', 'Implement machine learning-based anomaly detection.', 'Expand monitoring coverage.'], auditor_questions: ['What anomalies are detected?', 'How are anomalies investigated?', 'Describe threat detection capabilities.', 'Show evidence of anomaly response.'], analyzed_at: completed },
      { control_id: 'CC7.4', name: 'Incident Response', status: 'fail', gap_score: 48, freshness_score: 100, summary: 'GuardDuty disabled in eu-west-1; SecurityHub reports 7 active HIGH findings older than 30 days.', findings: [{ id: 'f3', severity: 'HIGH', title: 'GuardDuty disabled in eu-west-1', description: 'No detector in active region with workloads.', evidence_id: 'ev_demo_3', remediation: 'aws guardduty create-detector --enable' }, { id: 'f6', severity: 'HIGH', title: '7 active HIGH SecurityHub findings', description: 'Findings older than 30 days indicate inadequate incident response.', evidence_id: 'ev_demo_8', remediation: 'aws securityhub batch-update-findings --finding-identifiers Id=arn:aws:securityhub:us-east-1:743820195634:subscription/cis-aws-foundations-benchmark/v/1.2.0/1.5/finding/123 --note-text "Resolved" --workflow Status=RESOLVED' }], evidence_ids: ['ev_demo_3', 'ev_demo_8'], recommendations: ['Enable GuardDuty everywhere; ingest findings to SIEM.', 'Implement automated finding remediation.', 'Develop incident response playbooks.', 'Set up 24/7 monitoring.'], auditor_questions: ['Describe the incident response process.', 'How are security findings triaged?', 'What tools support incident response?', 'Show evidence of incident handling.'], analyzed_at: completed },
      { control_id: 'CC8.1', name: 'Change Management', status: 'pass', gap_score: 82, freshness_score: 100, summary: 'CloudTrail captures 100% of change events; Config records resource history; Lambda functions tagged with version + commit SHA.', findings: [], evidence_ids: ['ev_demo_9', 'ev_demo_13', 'ev_demo_22'], recommendations: ['Implement change approval workflows.', 'Automate change tracking.', 'Regular change audits.'], auditor_questions: ['How are changes managed and approved?', 'What change tracking exists?', 'Describe deployment processes.', 'Show evidence of change controls.'], analyzed_at: completed },
      { control_id: 'CC9.2', name: 'Business Continuity & Recovery — AWS Layer Only', status: 'fail', gap_score: 38, freshness_score: 100, audit_risk: 'CRITICAL', summary: 'Recovery procedures and BCDR governance are outside AWS API assessment scope. Within the technical layer: acmepay-prod-billing RDS has 0-day backup retention and is single-AZ. Other instances are configured correctly.', findings: [{ id: 'f4', severity: 'CRITICAL', title: 'Production RDS without backups', description: 'acmepay-prod-billing — BackupRetentionPeriod=0, MultiAZ=false. Data loss on instance failure would be unrecoverable beyond the most recent transaction log flush.', evidence_id: 'ev_demo_4', remediation: 'aws rds modify-db-instance --db-instance-identifier acmepay-prod-billing --backup-retention-period 7 --multi-az --apply-immediately' }], evidence_ids: ['ev_demo_4', 'ev_demo_20'], recommendations: ['Set BackupRetentionPeriod ≥ 7 days for all production RDS.', 'Enable MultiAZ on acmepay-prod-billing.', 'Document RPO/RTO targets and provide them to your auditor — the API cannot verify these.', 'Implement automated backup testing.'], auditor_questions: ['What is your documented RPO and RTO for acmepay-prod-billing?', 'When was the last successful restore-from-backup test, and where is the runbook?', 'How are backups validated?', 'Describe disaster recovery capabilities.'], partially_assessable: true, disclaimers: ['Recovery procedures and testing outside technical scope. RTO/RPO targets and tabletop exercises must be evaluated by your auditor separately.'], analyzed_at: completed },
    ],
  };
  return {
    id: 'demo_acmepay',
    org_name: 'AcmePay, Inc.',
    results,
    created_at: created,
    completed_at: completed,
    evidence_count: 847,
  };
}
