// Hardcoded demo scan — "AcmePay, Inc." — used by GET /api/demo so prospects
// can see a complete report before connecting AWS.

import type { ScanResults } from './types';

export function demoScan(): { id: string; org_name: string; results: ScanResults; created_at: number; completed_at: number; evidence_count: number } {
  const created = Date.now() - 1000 * 60 * 12;
  const completed = created + 1000 * 60 * 7;
  const results: ScanResults = {
    executive_summary:
      'AcmePay, Inc. scanned 12 SOC 2 controls. 5 pass, 4 partial, 2 fail, 1 inconclusive. Overall readiness: Near-ready. Average gap score 64/100, freshness 92/100. Critical work: enforce MFA on all IAM users, enable GuardDuty in eu-west-1, and configure RDS automated backups for `acmepay-prod-billing`.',
    overall_readiness: 'Near-ready',
    overall_gap_score: 64,
    overall_freshness_score: 92,
    critical_actions: [
      '[CC6.1] 3 IAM users without MFA — Enforce MFA via permission boundary policy',
      '[CC7.4] GuardDuty disabled in eu-west-1 — Enable GuardDuty across all active regions',
      '[CC9.2] acmepay-prod-billing RDS instance has 0-day backup retention — Set to ≥7 days',
      '[CC6.6] 2 S3 buckets allow public read — Apply bucket-level public access block',
      '[CC8.1] CloudTrail multi-region trail not enabled in 1 region — Enable management+data events',
    ],
    strengths: [
      'CC6.7: Restricted Data Movement & Encryption',
      'CC7.1: Configuration & Vulnerability Management',
      'CC7.2: Security Event Monitoring',
      'CC6.3: Role-Based Access & Segregation of Duties',
      'CC8.1: Change Management',
    ],
    evidence: [
      // IAM
      { id: 'ev_demo_1', service: 'iam', region: 'global', api: 'GetAccountSummary', timestamp: created, raw: '<GetAccountSummaryResponse><AccountMFAEnabled>1</AccountMFAEnabled><Users>14</Users><MFADevices>11</MFADevices></GetAccountSummaryResponse>', rawBytes: 412, truncated: false, severity: 'HIGH', controls: ['CC6.1', 'CC6.2'], summary: '3 of 14 IAM users without MFA — alice@acmepay.com, dev1@acmepay.com, contractor-bob' },
      { id: 'ev_demo_1b', service: 'iam', region: 'global', api: 'GetAccountPasswordPolicy', timestamp: created, raw: '{"PasswordPolicy":{"MinimumPasswordLength":14,"RequireSymbols":true,"RequireNumbers":true,"RequireUppercaseCharacters":true,"MaxPasswordAge":90,"PasswordReusePrevention":12}}', rawBytes: 189, truncated: false, severity: 'INFO', controls: ['CC6.1'], summary: 'Password policy meets CIS benchmark — 14 char min, 90-day expiry, no reuse for 12' },
      { id: 'ev_demo_1c', service: 'iam', region: 'global', api: 'ListUsers', timestamp: created, raw: '{"Users":[{"UserName":"alice","Arn":"arn:aws:iam::743820195634:user/alice","CreateDate":"2023-01-15"},{"UserName":"dev1","Arn":"arn:aws:iam::743820195634:user/dev1","CreateDate":"2023-06-01"},{"UserName":"contractor-bob","Arn":"arn:aws:iam::743820195634:user/contractor-bob","CreateDate":"2024-09-12"}]}', rawBytes: 345, truncated: false, severity: 'MEDIUM', controls: ['CC6.1', 'CC6.3'], summary: '3 users without MFA: alice, dev1, contractor-bob' },
      { id: 'ev_demo_1d', service: 'iam', region: 'global', api: 'ListRoles', timestamp: created, raw: '{"Roles":[{"RoleName":"acmepay-prod-deploy","Arn":"arn:aws:iam::743820195634:role/acmepay-prod-deploy"},{"RoleName":"acmepay-readonly","Arn":"arn:aws:iam::743820195634:role/acmepay-readonly"},{"RoleName":"acmepay-billing-admin","Arn":"arn:aws:iam::743820195634:role/acmepay-billing-admin"}]}', rawBytes: 278, truncated: false, severity: 'INFO', controls: ['CC6.3'], summary: '3 service roles — prod-deploy, readonly, billing-admin — all scoped' },
      { id: 'ev_demo_1e', service: 'iam', region: 'global', api: 'ListPolicies', timestamp: created, raw: '{"Policies":[{"PolicyName":"AcmepayProdDeploy","Arn":"arn:aws:iam::743820195634:policy/AcmepayProdDeploy","AttachmentCount":1},{"PolicyName":"AcmepayReadOnly","Arn":"arn:aws:iam::743820195634:policy/AcmepayReadOnly","AttachmentCount":3}]}', rawBytes: 267, truncated: false, severity: 'INFO', controls: ['CC6.3'], summary: 'Customer-managed policies — no wildcard actions detected' },
      { id: 'ev_demo_1f', service: 'iam', region: 'global', api: 'GetCredentialReport', timestamp: created, raw: 'user,arn,user_creation_time,password_enabled,password_last_used,mfa_active\nalice,arn:aws:iam::743820195634:user/alice,2023-01-15T00:00:00+00:00,true,2026-05-01T09:00:00+00:00,false\ndev1,arn:aws:iam::743820195634:user/dev1,2023-06-01T00:00:00+00:00,true,2026-04-28T14:00:00+00:00,false', rawBytes: 312, truncated: false, severity: 'HIGH', controls: ['CC6.1'], summary: 'Credential report: alice and dev1 active console users with no MFA, last login within 30 days' },
      // GuardDuty
      { id: 'ev_demo_2', service: 'guardduty', region: 'us-east-1', api: 'GetDetector', timestamp: created, raw: '{"Status":"ENABLED","FindingPublishingFrequency":"FIFTEEN_MINUTES","DataSources":{"CloudTrail":{"Status":"ENABLED"},"S3Logs":{"Status":"ENABLED"},"Kubernetes":{"AuditLogs":{"Status":"ENABLED"}}}}', rawBytes: 234, truncated: false, severity: 'INFO', controls: ['CC7.4', 'CC7.3'], summary: 'GuardDuty enabled in us-east-1 — CloudTrail, S3, K8s sources active' },
      { id: 'ev_demo_2b', service: 'guardduty', region: 'us-west-2', api: 'GetDetector', timestamp: created, raw: '{"Status":"ENABLED","FindingPublishingFrequency":"ONE_HOUR","DataSources":{"CloudTrail":{"Status":"ENABLED"},"S3Logs":{"Status":"ENABLED"}}}', rawBytes: 178, truncated: false, severity: 'INFO', controls: ['CC7.4'], summary: 'GuardDuty enabled in us-west-2' },
      { id: 'ev_demo_2c', service: 'guardduty', region: 'eu-central-1', api: 'GetDetector', timestamp: created, raw: '{"Status":"ENABLED","FindingPublishingFrequency":"FIFTEEN_MINUTES","DataSources":{"CloudTrail":{"Status":"ENABLED"}}}', rawBytes: 156, truncated: false, severity: 'INFO', controls: ['CC7.4'], summary: 'GuardDuty enabled in eu-central-1' },
      { id: 'ev_demo_3', service: 'guardduty', region: 'eu-west-1', api: 'ListDetectors', timestamp: created, raw: '{"DetectorIds":[]}', rawBytes: 18, truncated: false, severity: 'HIGH', controls: ['CC7.4'], summary: 'No GuardDuty detector in eu-west-1 — workloads present in this region' },
      { id: 'ev_demo_2d', service: 'guardduty', region: 'us-east-1', api: 'ListFindings', timestamp: created, raw: '{"FindingIds":["abc123","def456","ghi789"]}', rawBytes: 67, truncated: false, severity: 'MEDIUM', controls: ['CC7.4', 'CC7.3'], summary: '3 active GuardDuty findings in us-east-1 — all MEDIUM severity' },
      // RDS
      { id: 'ev_demo_4', service: 'rds', region: 'us-east-1', api: 'DescribeDBInstances', timestamp: created, raw: '{"DBInstances":[{"DBInstanceIdentifier":"acmepay-prod-billing","BackupRetentionPeriod":0,"MultiAZ":false,"StorageEncrypted":true,"EngineVersion":"14.7","DBInstanceClass":"db.r6g.xlarge","DeletionProtection":false}]}', rawBytes: 568, truncated: false, severity: 'CRITICAL', controls: ['CC9.2', 'CC6.7'], summary: 'acmepay-prod-billing: 0-day backup, single-AZ, deletion protection off — production data at risk' },
      { id: 'ev_demo_4b', service: 'rds', region: 'us-east-1', api: 'DescribeDBInstances', timestamp: created, raw: '{"DBInstances":[{"DBInstanceIdentifier":"acmepay-prod-users","BackupRetentionPeriod":7,"MultiAZ":true,"StorageEncrypted":true,"EngineVersion":"14.7","DBInstanceClass":"db.r6g.2xlarge","DeletionProtection":true}]}', rawBytes: 423, truncated: false, severity: 'INFO', controls: ['CC9.2', 'CC6.7'], summary: 'acmepay-prod-users: 7-day backup, Multi-AZ, encrypted, deletion protection on — compliant' },
      { id: 'ev_demo_4c', service: 'rds', region: 'us-east-1', api: 'DescribeDBSnapshots', timestamp: created, raw: '{"DBSnapshots":[{"DBSnapshotIdentifier":"acmepay-prod-users-2026-05-01","SnapshotCreateTime":"2026-05-01T03:00:00Z","Status":"available","Encrypted":true}]}', rawBytes: 234, truncated: false, severity: 'INFO', controls: ['CC9.2'], summary: 'acmepay-prod-users: automated snapshot from 2026-05-01 confirmed available' },
      { id: 'ev_demo_4d', service: 'rds', region: 'eu-west-1', api: 'DescribeDBInstances', timestamp: created, raw: '{"DBInstances":[{"DBInstanceIdentifier":"acmepay-eu-reporting","BackupRetentionPeriod":14,"MultiAZ":false,"StorageEncrypted":true,"EngineVersion":"13.9","DBInstanceClass":"db.t3.medium"}]}', rawBytes: 312, truncated: false, severity: 'LOW', controls: ['CC9.2'], summary: 'acmepay-eu-reporting: 14-day backup, single-AZ (non-production), encrypted' },
      // S3
      { id: 'ev_demo_5', service: 's3', region: 'global', api: 'GetPublicAccessBlock', timestamp: created, raw: '{"Buckets":["acmepay-public-assets","acmepay-marketing-2024"],"PublicReadAllowed":true,"BlockPublicAcls":false,"IgnorePublicAcls":false}', rawBytes: 145, truncated: false, severity: 'HIGH', controls: ['CC6.6'], summary: 'acmepay-public-assets and acmepay-marketing-2024 allow public read — no block policy' },
      { id: 'ev_demo_5b', service: 's3', region: 'global', api: 'GetBucketEncryption', timestamp: created, raw: '{"Buckets":[{"Name":"acmepay-data-lake","ServerSideEncryptionConfiguration":{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"aws:kms","KMSMasterKeyID":"arn:aws:kms:us-east-1:743820195634:key/mrk-abc123"}}]}}]}', rawBytes: 312, truncated: false, severity: 'INFO', controls: ['CC6.7'], summary: 'acmepay-data-lake: SSE-KMS with customer-managed key confirmed' },
      { id: 'ev_demo_5c', service: 's3', region: 'global', api: 'GetBucketVersioning', timestamp: created, raw: '{"Bucket":"acmepay-data-lake","Status":"Enabled","MFADelete":"Disabled"}', rawBytes: 78, truncated: false, severity: 'INFO', controls: ['CC9.2'], summary: 'acmepay-data-lake: versioning enabled, MFA delete not enforced' },
      { id: 'ev_demo_5d', service: 's3', region: 'global', api: 'GetBucketLogging', timestamp: created, raw: '{"Bucket":"acmepay-data-lake","LoggingEnabled":{"TargetBucket":"acmepay-access-logs","TargetPrefix":"data-lake/"}}', rawBytes: 123, truncated: false, severity: 'INFO', controls: ['CC7.2'], summary: 'acmepay-data-lake: server access logging to acmepay-access-logs' },
      { id: 'ev_demo_5e', service: 's3', region: 'global', api: 'ListBuckets', timestamp: created, raw: '{"Buckets":[{"Name":"acmepay-data-lake"},{"Name":"acmepay-public-assets"},{"Name":"acmepay-marketing-2024"},{"Name":"acmepay-access-logs"},{"Name":"acmepay-terraform-state"},{"Name":"acmepay-cloudtrail-logs"}],"Owner":{"DisplayName":"acmepay-root"}}', rawBytes: 289, truncated: false, severity: 'INFO', controls: ['CC6.6', 'CC6.7'], summary: '6 S3 buckets — 2 with public read issues identified' },
      // Config
      { id: 'ev_demo_6', service: 'config', region: 'us-east-1', api: 'DescribeConfigurationRecorderStatus', timestamp: created, raw: '{"ConfigurationRecordersStatus":[{"name":"default","lastStartTime":"2026-01-01T00:00:00Z","recording":true,"lastStatus":"SUCCESS"}]}', rawBytes: 167, truncated: false, severity: 'INFO', controls: ['CC5.2', 'CC7.1'], summary: 'AWS Config recording active in us-east-1 since 2026-01-01' },
      { id: 'ev_demo_6b', service: 'config', region: 'us-east-1', api: 'DescribeConfigRules', timestamp: created, raw: '{"ConfigRules":[{"ConfigRuleName":"mfa-enabled-for-iam-console-access","ComplianceTypes":["NON_COMPLIANT"]},{"ConfigRuleName":"s3-bucket-public-read-prohibited","ComplianceTypes":["NON_COMPLIANT"]},{"ConfigRuleName":"rds-automatic-minor-version-upgrade-enabled","ComplianceTypes":["COMPLIANT"]},{"ConfigRuleName":"cloudtrail-enabled","ComplianceTypes":["COMPLIANT"]}]}', rawBytes: 456, truncated: false, severity: 'MEDIUM', controls: ['CC7.1', 'CC5.2'], summary: '4 Config rules: 2 NON_COMPLIANT (MFA, S3 public read), 2 COMPLIANT' },
      { id: 'ev_demo_6c', service: 'config', region: 'eu-west-1', api: 'DescribeConfigurationRecorderStatus', timestamp: created, raw: '{"ConfigurationRecordersStatus":[]}', rawBytes: 32, truncated: false, severity: 'MEDIUM', controls: ['CC5.2'], summary: 'AWS Config not enabled in eu-west-1' },
      { id: 'ev_demo_6d', service: 'config', region: 'us-east-1', api: 'GetComplianceSummaryByConfigRule', timestamp: created, raw: '{"ComplianceSummaryByConfigRules":{"CompliantRuleCount":18,"NonCompliantRuleCount":2,"TotalRuleCount":20}}', rawBytes: 123, truncated: false, severity: 'INFO', controls: ['CC7.1'], summary: '18/20 Config rules compliant — 90% compliance rate' },
      // SecurityHub
      { id: 'ev_demo_8', service: 'securityhub', region: 'us-east-1', api: 'GetFindings', timestamp: created, raw: '{"Findings":[{"Id":"arn:aws:securityhub:us-east-1:743820195634:subscription/cis-aws-foundations-benchmark/v/1.2.0/1.5/finding/abc","Severity":{"Label":"HIGH"},"Title":"1.5 Ensure MFA is enabled for the root account","RecordState":"ACTIVE","CreatedAt":"2026-03-01"},{"Id":"arn:aws:securityhub:us-east-1:743820195634:subscription/aws-foundational-security-best-practices/v/1.0.0/S3.2/finding/def","Severity":{"Label":"HIGH"},"Title":"S3.2 S3 buckets should prohibit public read access","RecordState":"ACTIVE","CreatedAt":"2026-02-15"}]}', rawBytes: 789, truncated: false, severity: 'HIGH', controls: ['CC7.4', 'CC6.1'], summary: '7 active HIGH SecurityHub findings — 2 shown: root MFA, S3 public read' },
      { id: 'ev_demo_8b', service: 'securityhub', region: 'us-east-1', api: 'GetEnabledStandards', timestamp: created, raw: '{"StandardsSubscriptions":[{"StandardsArn":"arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0","StandardsStatus":"READY"},{"StandardsArn":"arn:aws:securityhub:us-east-1::standards/aws-foundational-security-best-practices/v/1.0.0","StandardsStatus":"READY"}]}', rawBytes: 345, truncated: false, severity: 'INFO', controls: ['CC7.1'], summary: 'CIS Foundations + AWS FSBP standards enabled and active' },
      // CloudTrail
      { id: 'ev_demo_9', service: 'cloudtrail', region: 'us-east-1', api: 'DescribeTrails', timestamp: created, raw: '{"trailList":[{"Name":"acmepay-org-trail","S3BucketName":"acmepay-cloudtrail-logs","IsMultiRegionTrail":true,"IncludeGlobalServiceEvents":true,"IsOrganizationTrail":true,"HasCustomEventSelectors":true,"LogFileValidationEnabled":true}]}', rawBytes: 389, truncated: false, severity: 'INFO', controls: ['CC7.2', 'CC8.1'], summary: 'Multi-region org trail with log validation — covers management + data events' },
      { id: 'ev_demo_9b', service: 'cloudtrail', region: 'us-east-1', api: 'GetTrailStatus', timestamp: created, raw: '{"IsLogging":true,"LatestDeliveryTime":"2026-05-06T17:45:00Z","LatestDeliveryError":null,"StartLoggingTime":"2023-01-01T00:00:00Z"}', rawBytes: 156, truncated: false, severity: 'INFO', controls: ['CC7.2'], summary: 'CloudTrail actively logging — last delivery 2026-05-06 17:45 UTC, no errors' },
      { id: 'ev_demo_9c', service: 'cloudtrail', region: 'us-east-1', api: 'LookupEvents', timestamp: created, raw: '{"Events":[{"EventId":"evt-123","EventName":"DeleteBucket","Username":"alice","EventTime":"2026-04-28T14:22:00Z","Resources":[{"ResourceName":"acmepay-temp-test"}]},{"EventId":"evt-456","EventName":"PutBucketPolicy","Username":"alice","EventTime":"2026-04-28T14:20:00Z"}]}', rawBytes: 423, truncated: false, severity: 'MEDIUM', controls: ['CC8.1', 'CC7.2'], summary: 'Recent events: alice deleted acmepay-temp-test bucket and modified bucket policy on 2026-04-28' },
      // KMS
      { id: 'ev_demo_10', service: 'kms', region: 'us-east-1', api: 'ListKeys', timestamp: created, raw: '{"Keys":[{"KeyId":"mrk-abc123","KeyArn":"arn:aws:kms:us-east-1:743820195634:key/mrk-abc123"},{"KeyId":"mrk-def456","KeyArn":"arn:aws:kms:us-east-1:743820195634:key/mrk-def456"},{"KeyId":"mrk-ghi789","KeyArn":"arn:aws:kms:us-east-1:743820195634:key/mrk-ghi789"}]}', rawBytes: 312, truncated: false, severity: 'INFO', controls: ['CC6.7'], summary: '3 customer-managed KMS keys in us-east-1' },
      { id: 'ev_demo_10b', service: 'kms', region: 'us-east-1', api: 'GetKeyRotationStatus', timestamp: created, raw: '{"KeyId":"mrk-abc123","KeyRotationEnabled":true,"NextRotationDate":"2027-01-15T00:00:00Z"}', rawBytes: 98, truncated: false, severity: 'INFO', controls: ['CC6.7'], summary: 'KMS key mrk-abc123: automatic rotation enabled, next rotation 2027-01-15' },
      { id: 'ev_demo_10c', service: 'kms', region: 'us-east-1', api: 'GetKeyRotationStatus', timestamp: created, raw: '{"KeyId":"mrk-def456","KeyRotationEnabled":false}', rawBytes: 54, truncated: false, severity: 'MEDIUM', controls: ['CC6.7'], summary: 'KMS key mrk-def456: rotation NOT enabled — used for RDS encryption' },
      // EC2 / VPC
      { id: 'ev_demo_11', service: 'ec2', region: 'us-east-1', api: 'DescribeSecurityGroups', timestamp: created, raw: '{"SecurityGroups":[{"GroupId":"sg-12345","GroupName":"acmepay-bastion","IpPermissions":[{"IpProtocol":"tcp","FromPort":22,"ToPort":22,"IpRanges":[{"CidrIp":"0.0.0.0/0"}]}]}]}', rawBytes: 245, truncated: false, severity: 'HIGH', controls: ['CC6.6'], summary: 'sg-12345 (acmepay-bastion): SSH port 22 open to 0.0.0.0/0' },
      { id: 'ev_demo_11b', service: 'ec2', region: 'us-east-1', api: 'DescribeSecurityGroups', timestamp: created, raw: '{"SecurityGroups":[{"GroupId":"sg-67890","GroupName":"acmepay-app-tier","IpPermissions":[{"IpProtocol":"tcp","FromPort":443,"ToPort":443,"IpRanges":[{"CidrIp":"0.0.0.0/0"}]}]}]}', rawBytes: 198, truncated: false, severity: 'INFO', controls: ['CC6.6'], summary: 'sg-67890 (acmepay-app-tier): HTTPS only, no unrestricted admin ports' },
      { id: 'ev_demo_11c', service: 'ec2', region: 'us-east-1', api: 'DescribeFlowLogs', timestamp: created, raw: '{"FlowLogs":[{"FlowLogId":"fl-123","ResourceId":"vpc-acmepay-prod","FlowLogStatus":"ACTIVE","TrafficType":"ALL","LogDestinationType":"cloud-watch-logs"}]}', rawBytes: 189, truncated: false, severity: 'INFO', controls: ['CC6.6', 'CC7.2'], summary: 'VPC Flow Logs enabled on acmepay-prod VPC — all traffic to CloudWatch' },
      { id: 'ev_demo_12', service: 'ec2', region: 'us-east-1', api: 'DescribeVpcs', timestamp: created, raw: '{"Vpcs":[{"VpcId":"vpc-acmepay-prod","CidrBlock":"10.0.0.0/16","IsDefault":false,"Tags":[{"Key":"Name","Value":"acmepay-prod"}]},{"VpcId":"vpc-acmepay-dev","CidrBlock":"10.1.0.0/16","IsDefault":false}]}', rawBytes: 245, truncated: false, severity: 'INFO', controls: ['CC6.6'], summary: '2 VPCs: acmepay-prod (10.0.0.0/16) and acmepay-dev (10.1.0.0/16) — no default VPC in use' },
      { id: 'ev_demo_11d', service: 'ec2', region: 'eu-west-1', api: 'DescribeFlowLogs', timestamp: created, raw: '{"FlowLogs":[]}', rawBytes: 16, truncated: false, severity: 'MEDIUM', controls: ['CC6.6', 'CC7.2'], summary: 'No VPC Flow Logs in eu-west-1 — traffic not captured' },
      // Lambda
      { id: 'ev_demo_13', service: 'lambda', region: 'us-east-1', api: 'ListFunctions', timestamp: created, raw: '{"Functions":[{"FunctionName":"acmepay-payment-processor","Runtime":"nodejs18.x","LastModified":"2026-04-15T10:00:00Z","Description":"Handles payment processing"},{"FunctionName":"acmepay-fraud-detection","Runtime":"python3.11","LastModified":"2026-04-20T14:00:00Z"},{"FunctionName":"acmepay-reconciliation","Runtime":"nodejs18.x","LastModified":"2026-03-01T09:00:00Z"}]}', rawBytes: 456, truncated: false, severity: 'INFO', controls: ['CC8.1'], summary: '3 Lambda functions — payment-processor, fraud-detection, reconciliation — all recent deploys' },
      { id: 'ev_demo_13b', service: 'lambda', region: 'us-east-1', api: 'GetFunctionConcurrency', timestamp: created, raw: '{"FunctionName":"acmepay-payment-processor","ReservedConcurrentExecutions":100}', rawBytes: 89, truncated: false, severity: 'INFO', controls: ['CC9.2'], summary: 'acmepay-payment-processor: 100 reserved concurrency — production isolation configured' },
      // WAF / ALB
      { id: 'ev_demo_14', service: 'waf', region: 'global', api: 'ListWebACLs', timestamp: created, raw: '{"WebACLs":[{"WebACLId":"waf-acmepay-prod","Name":"acmepay-waf-prod","DefaultAction":{"Type":"BLOCK"}}]}', rawBytes: 145, truncated: false, severity: 'INFO', controls: ['CC6.6'], summary: 'WAF ACL acmepay-waf-prod — default action BLOCK, protects 3 ALBs' },
      { id: 'ev_demo_17', service: 'ec2', region: 'us-east-1', api: 'DescribeLoadBalancers', timestamp: created, raw: '{"LoadBalancers":[{"LoadBalancerArn":"arn:aws:elasticloadbalancing:us-east-1:743820195634:loadbalancer/app/acmepay-alb-prod/abc","Scheme":"internet-facing","State":{"Code":"active"}},{"LoadBalancerArn":"arn:aws:elasticloadbalancing:us-east-1:743820195634:loadbalancer/app/acmepay-alb-internal/def","Scheme":"internal"}]}', rawBytes: 378, truncated: false, severity: 'INFO', controls: ['CC6.6'], summary: '2 ALBs: acmepay-alb-prod (internet-facing, WAF attached) and acmepay-alb-internal' },
      // CloudWatch / SNS
      { id: 'ev_demo_15', service: 'cloudwatch', region: 'us-east-1', api: 'DescribeAlarms', timestamp: created, raw: '{"MetricAlarms":[{"AlarmName":"acmepay-root-login","StateValue":"OK","AlarmActions":["arn:aws:sns:us-east-1:743820195634:acmepay-security-alerts"]},{"AlarmName":"acmepay-billing-threshold","StateValue":"OK"},{"AlarmName":"acmepay-4xx-rate","StateValue":"ALARM","StateReason":"Threshold breached"},{"AlarmName":"acmepay-unauthorized-api","StateValue":"OK"}]}', rawBytes: 456, truncated: false, severity: 'MEDIUM', controls: ['CC7.3', 'CC7.2'], summary: '4 CloudWatch alarms — 1 in ALARM state (4xx rate), 3 OK including root login and unauthorized API' },
      { id: 'ev_demo_16', service: 'sns', region: 'us-east-1', api: 'ListTopics', timestamp: created, raw: '{"Topics":[{"TopicArn":"arn:aws:sns:us-east-1:743820195634:acmepay-security-alerts"},{"TopicArn":"arn:aws:sns:us-east-1:743820195634:acmepay-ops-alerts"}]}', rawBytes: 178, truncated: false, severity: 'INFO', controls: ['CC7.3'], summary: 'SNS: acmepay-security-alerts (PagerDuty) and acmepay-ops-alerts (Slack) active' },
      { id: 'ev_demo_15b', service: 'cloudwatch', region: 'us-east-1', api: 'DescribeLogGroups', timestamp: created, raw: '{"logGroups":[{"logGroupName":"/aws/lambda/acmepay-payment-processor","retentionInDays":90},{"logGroupName":"/aws/lambda/acmepay-fraud-detection","retentionInDays":365},{"logGroupName":"/aws/vpc/flowlogs/acmepay-prod","retentionInDays":180}]}', rawBytes: 312, truncated: false, severity: 'INFO', controls: ['CC7.2'], summary: '3 log groups — 90/365/180 day retention for Lambda and VPC flow logs' },
      // Organizations / SSO
      { id: 'ev_demo_18', service: 'organizations', region: 'global', api: 'DescribeOrganization', timestamp: created, raw: '{"Organization":{"Id":"o-acmepay123","MasterAccountId":"743820195634","FeatureSet":"ALL","AvailablePolicyTypes":[{"Type":"SERVICE_CONTROL_POLICY","Status":"ENABLED"}]}}', rawBytes: 189, truncated: false, severity: 'INFO', controls: ['CC6.3'], summary: 'AWS Organization with SCP enabled — master account 743820195634' },
      { id: 'ev_demo_18b', service: 'organizations', region: 'global', api: 'ListPolicies', timestamp: created, raw: '{"Policies":[{"Id":"p-abc123","Name":"DenyPublicS3","Type":"SERVICE_CONTROL_POLICY"},{"Id":"p-def456","Name":"RequireMFA","Type":"SERVICE_CONTROL_POLICY"},{"Id":"p-ghi789","Name":"DenyRootAccess","Type":"SERVICE_CONTROL_POLICY"}]}', rawBytes: 267, truncated: false, severity: 'INFO', controls: ['CC6.1', 'CC6.6'], summary: '3 SCPs: DenyPublicS3, RequireMFA (not catching all users), DenyRootAccess' },
      { id: 'ev_demo_19', service: 'sso', region: 'global', api: 'ListInstances', timestamp: created, raw: '{"Instances":[{"InstanceArn":"arn:aws:sso:::instance/ssoins-acmepay","IdentityStoreId":"d-acmepay123","CreatedDate":"2023-06-01T00:00:00Z"}]}', rawBytes: 156, truncated: false, severity: 'INFO', controls: ['CC6.1', 'CC6.2'], summary: 'AWS IAM Identity Center (SSO) active since 2023-06-01' },
      { id: 'ev_demo_19b', service: 'sso', region: 'global', api: 'ListPermissionSets', timestamp: created, raw: '{"PermissionSets":["arn:aws:sso:::permissionSet/ssoins-acmepay/ps-admin","arn:aws:sso:::permissionSet/ssoins-acmepay/ps-developer","arn:aws:sso:::permissionSet/ssoins-acmepay/ps-readonly","arn:aws:sso:::permissionSet/ssoins-acmepay/ps-billing"]}', rawBytes: 312, truncated: false, severity: 'INFO', controls: ['CC6.3'], summary: '4 permission sets: admin, developer, readonly, billing — appropriate segregation' },
      // Backup
      { id: 'ev_demo_20', service: 'backup', region: 'us-east-1', api: 'ListBackupVaults', timestamp: created, raw: '{"BackupVaultList":[{"BackupVaultName":"acmepay-prod-vault","NumberOfRecoveryPoints":847,"BackupVaultArn":"arn:aws:backup:us-east-1:743820195634:backup-vault:acmepay-prod-vault"}]}', rawBytes: 189, truncated: false, severity: 'INFO', controls: ['CC9.2'], summary: 'acmepay-prod-vault: 847 recovery points — active backup coverage' },
      { id: 'ev_demo_20b', service: 'backup', region: 'us-east-1', api: 'ListBackupPlans', timestamp: created, raw: '{"BackupPlansList":[{"BackupPlanId":"plan-abc123","BackupPlanName":"acmepay-prod-daily","CreationDate":"2023-06-01","LastExecutionDate":"2026-05-05T03:00:00Z"}]}', rawBytes: 178, truncated: false, severity: 'INFO', controls: ['CC9.2'], summary: 'acmepay-prod-daily backup plan: last run 2026-05-05 03:00 UTC — successful' },
      // Secrets Manager
      { id: 'ev_demo_secmgr1', service: 'secretsmanager', region: 'us-east-1', api: 'ListSecrets', timestamp: created, raw: '{"SecretList":[{"Name":"acmepay/prod/db-password","LastRotatedDate":"2026-04-01T00:00:00Z","RotationEnabled":true},{"Name":"acmepay/prod/stripe-api-key","LastRotatedDate":null,"RotationEnabled":false},{"Name":"acmepay/prod/internal-jwt-secret","LastRotatedDate":"2026-03-15T00:00:00Z","RotationEnabled":true}]}', rawBytes: 345, truncated: false, severity: 'MEDIUM', controls: ['CC6.1', 'CC6.7'], summary: '3 secrets — db-password and jwt-secret have auto-rotation; stripe-api-key does not' },
      // Route53 / CF / Support
      { id: 'ev_demo_21', service: 'route53', region: 'global', api: 'ListHostedZones', timestamp: created, raw: '{"HostedZones":[{"Id":"/hostedzone/Z12345","Name":"acmepay.com.","Config":{"PrivateZone":false}},{"Id":"/hostedzone/Z67890","Name":"internal.acmepay.com.","Config":{"PrivateZone":true}}]}', rawBytes: 189, truncated: false, severity: 'INFO', controls: ['CC6.6'], summary: 'Route53: acmepay.com (public) and internal.acmepay.com (private) — split-horizon DNS' },
      { id: 'ev_demo_22', service: 'cloudformation', region: 'us-east-1', api: 'ListStacks', timestamp: created, raw: '{"StackSummaries":[{"StackName":"acmepay-infra-prod","StackStatus":"UPDATE_COMPLETE","LastUpdatedTime":"2026-04-30T14:00:00Z"},{"StackName":"acmepay-network","StackStatus":"CREATE_COMPLETE","LastUpdatedTime":"2023-06-01T00:00:00Z"},{"StackName":"acmepay-iam","StackStatus":"UPDATE_COMPLETE","LastUpdatedTime":"2026-04-15T09:00:00Z"}]}', rawBytes: 345, truncated: false, severity: 'INFO', controls: ['CC8.1'], summary: '3 CloudFormation stacks: infra-prod (updated 2026-04-30), network, iam-roles' },
      { id: 'ev_demo_23', service: 'trustedadvisor', region: 'global', api: 'DescribeTrustedAdvisorChecks', timestamp: created, raw: '{"checks":[{"id":"HCP4007jnz","name":"Security Groups - Specific Ports Unrestricted","category":"security","status":"warning"},{"id":"Hs4Ma3G2JO","name":"MFA on Root Account","category":"security","status":"error"}]}', rawBytes: 267, truncated: false, severity: 'HIGH', controls: ['CC6.1', 'CC6.6'], summary: 'Trusted Advisor: 2 security checks flagged — unrestricted SG ports + root MFA' },
      // X-Ray / Misc
      { id: 'ev_demo_25', service: 'xray', region: 'us-east-1', api: 'GetSamplingRules', timestamp: created, raw: '{"SamplingRuleRecords":[{"SamplingRule":{"RuleName":"acmepay-payment","ResourceARN":"arn:aws:lambda:us-east-1:743820195634:function:acmepay-payment-processor","FixedRate":0.05,"ReservoirSize":5}},{"SamplingRule":{"RuleName":"default","ResourceARN":"*","Priority":10000,"FixedRate":0.05}}]}', rawBytes: 312, truncated: false, severity: 'INFO', controls: ['CC7.2'], summary: 'X-Ray tracing: acmepay-payment sampled at 5%, default rule active' },
      { id: 'ev_demo_26', service: 'iam', region: 'global', api: 'ListAccessKeys', timestamp: created, raw: '{"AccessKeyMetadata":[{"UserName":"deploy-ci","AccessKeyId":"AKIA...","Status":"Active","CreateDate":"2024-01-01T00:00:00Z"},{"UserName":"legacy-integration","AccessKeyId":"AKIA...","Status":"Active","CreateDate":"2022-06-15T00:00:00Z"}]}', rawBytes: 234, truncated: false, severity: 'MEDIUM', controls: ['CC6.1', 'CC6.3'], summary: 'deploy-ci key: 16 months old. legacy-integration key: 47 months old — rotation overdue' },
      { id: 'ev_demo_27', service: 'ec2', region: 'us-east-1', api: 'DescribeInstances', timestamp: created, raw: '{"Reservations":[{"Instances":[{"InstanceId":"i-abc123","InstanceType":"t3.medium","State":{"Name":"running"},"Tags":[{"Key":"Name","Value":"acmepay-bastion"},{"Key":"Environment","Value":"production"}],"MetadataOptions":{"HttpTokens":"required"}}]}]}', rawBytes: 345, truncated: false, severity: 'INFO', controls: ['CC6.6', 'CC7.1'], summary: 'acmepay-bastion: IMDSv2 enforced (HttpTokens=required) — SSRF protection active' },
      { id: 'ev_demo_28', service: 'ec2', region: 'us-east-1', api: 'DescribeSnapshots', timestamp: created, raw: '{"Snapshots":[{"SnapshotId":"snap-abc123","VolumeId":"vol-xyz","State":"completed","Encrypted":true,"StartTime":"2026-05-01T03:00:00Z"},{"SnapshotId":"snap-def456","VolumeId":"vol-abc","State":"completed","Encrypted":false,"StartTime":"2026-04-15T03:00:00Z"}]}', rawBytes: 289, truncated: false, severity: 'MEDIUM', controls: ['CC6.7', 'CC9.2'], summary: 'EBS snapshots: snap-abc123 encrypted, snap-def456 NOT encrypted — vol-abc unencrypted' },
      { id: 'ev_demo_29', service: 'ecr', region: 'us-east-1', api: 'DescribeRepositories', timestamp: created, raw: '{"repositories":[{"repositoryName":"acmepay-api","imageScanningConfiguration":{"scanOnPush":true},"imageTagMutability":"IMMUTABLE"},{"repositoryName":"acmepay-worker","imageScanningConfiguration":{"scanOnPush":false},"imageTagMutability":"MUTABLE"}]}', rawBytes: 312, truncated: false, severity: 'MEDIUM', controls: ['CC7.1', 'CC5.2'], summary: 'ECR: acmepay-api has scan-on-push + immutable tags; acmepay-worker does not' },
      { id: 'ev_demo_30', service: 'iam', region: 'global', api: 'GetAccountAuthorizationDetails', timestamp: created, raw: '{"UserDetailList":[{"UserName":"alice","GroupList":["developers"],"AttachedManagedPolicies":[]},{"UserName":"admin-root-break-glass","GroupList":["admins"],"AttachedManagedPolicies":[{"PolicyName":"AdministratorAccess"}]}],"GroupDetailList":[{"GroupName":"developers","AttachedManagedPolicies":[{"PolicyName":"AcmepayDeveloper"}]},{"GroupName":"admins","AttachedManagedPolicies":[{"PolicyName":"AdministratorAccess"}]}]}', rawBytes: 567, truncated: false, severity: 'INFO', controls: ['CC6.3'], summary: 'Break-glass admin account detected with AdministratorAccess — 1 human user with broad access' },
    ],
    controls: [
      { control_id: 'CC5.2', name: 'Technology Controls (Selection & Development)', status: 'partial', gap_score: 70, freshness_score: 95, summary: 'AWS Config rules enabled in 4/6 regions; SecurityHub standards (CIS, AWS Foundational) enabled. Process-level technology selection is outside technical scope.', findings: [], evidence_ids: ['ev_demo_6', 'ev_demo_7', 'ev_demo_24'], recommendations: ['Enable Config rules in eu-west-1 and ap-northeast-1.', 'Implement automated compliance monitoring.', 'Document technology selection criteria.', 'Regular security assessments of new tools.'], auditor_questions: ['What criteria are used for selecting cloud technologies?', 'How are security requirements integrated into technology selection?', 'Show evidence of vendor risk assessments.', 'Describe the process for evaluating new AWS services.'], partially_assessable: true, disclaimers: ['Process-level control selection out of technical scope.'], analyzed_at: completed },
      { control_id: 'CC6.1', name: 'Logical Access — Restricted Access', status: 'partial', gap_score: 58, freshness_score: 100, audit_risk: 'HIGH', summary: '3 of 14 IAM users have no MFA enabled. Password policy meets minimum requirements. KMS keys have rotation enabled.', findings: [{ id: 'f1', severity: 'HIGH', title: '3 IAM users without MFA', description: 'Users alice@acmepay.com, dev1@acmepay.com, contractor-bob have no MFA device registered. Per CC6.1 and CIS AWS 1.5, all IAM users with console access must have MFA.', evidence_id: 'ev_demo_1', remediation: 'aws iam enable-mfa-device --user-name alice --serial-number arn:aws:iam::743820195634:mfa/alice --authentication-code-1 123456 --authentication-code-2 789012' }], evidence_ids: ['ev_demo_1', 'ev_demo_19'], recommendations: ['Enforce MFA via SCP at the org level for all human IAM principals.', 'Migrate the three offending users to AWS SSO/Identity Center with enforced MFA.', 'Implement automated MFA compliance checks.', 'Set up MFA for all privileged accounts.'], auditor_questions: ['Show evidence that all IAM users with console access have MFA enrolled.', 'Walk through how a new employee gets IAM access — including approval, provisioning, and MFA enforcement.', 'What controls prevent MFA bypass?', 'How is MFA loss handled for emergency access?'], analyzed_at: completed },
      { control_id: 'CC6.2', name: 'System Access Provisioning', status: 'inconclusive', gap_score: 50, freshness_score: 80, summary: 'AWS shows IAM/SSO user creation timestamps but cannot validate provisioning approval workflow.', findings: [], evidence_ids: ['ev_demo_1', 'ev_demo_19'], recommendations: ['Provide HRIS-to-IAM provisioning runbook to your auditor.', 'Implement automated user lifecycle management.', 'Document access request and approval processes.', 'Set up regular access reviews.'], auditor_questions: ['Describe the user provisioning process from hire to access.', 'How are access rights reviewed and approved?', 'What happens when an employee leaves?', 'Show evidence of access provisioning controls.'], partially_assessable: true, disclaimers: ['Approval workflow out of technical scope.'], analyzed_at: completed },
      { control_id: 'CC6.3', name: 'Role-Based Access & Segregation of Duties', status: 'pass', gap_score: 88, freshness_score: 100, summary: 'IAM roles use least-privilege policies; SSO permission sets segregate duties; no wildcard admin grants outside break-glass role.', findings: [], evidence_ids: ['ev_demo_18'], recommendations: ['Continue regular policy reviews.', 'Implement automated policy analysis.', 'Document role definitions and responsibilities.'], auditor_questions: ['How are roles defined and assigned?', 'What segregation of duties controls exist?', 'Show examples of least-privilege policies.', 'Describe the break-glass access process.'], analyzed_at: completed },
      { control_id: 'CC6.6', name: 'External Threat Boundary', status: 'fail', gap_score: 42, freshness_score: 100, audit_risk: 'HIGH', summary: '2 S3 buckets allow public read access. WAF protects 3 of 4 ALBs. Security group allows SSH from anywhere.', findings: [{ id: 'f2', severity: 'HIGH', title: '2 S3 buckets allow public read', description: 'acmepay-public-assets and acmepay-marketing-2024 are missing PublicAccessBlock and have permissive bucket policies. Auditors will flag this against CC6.6 and CIS 2.1.5.', evidence_id: 'ev_demo_5', remediation: 'aws s3api put-public-access-block --bucket acmepay-public-assets --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true' }, { id: 'f5', severity: 'HIGH', title: 'SSH open to world', description: 'Security group sg-12345 allows SSH (port 22) from 0.0.0.0/0.', evidence_id: 'ev_demo_11', remediation: 'aws ec2 revoke-security-group-ingress --group-id sg-12345 --protocol tcp --port 22 --cidr 0.0.0.0/0' }], evidence_ids: ['ev_demo_5', 'ev_demo_11', 'ev_demo_14', 'ev_demo_17'], recommendations: ['Apply org-wide S3 BlockPublicAccess via SCP.', 'Add the fourth ALB to WAF coverage.', 'Restrict SSH access to specific IP ranges.', 'Implement network segmentation.'], auditor_questions: ['What controls prevent public S3 buckets from being created?', 'Provide CloudTrail evidence for the last 90 days of any public-bucket policy changes.', 'How is external access controlled?', 'Describe perimeter security measures.'], analyzed_at: completed },
      { control_id: 'CC6.7', name: 'Restricted Data Movement & Encryption', status: 'pass', gap_score: 90, freshness_score: 100, summary: 'All RDS instances encrypted at rest with customer-managed KMS keys. S3 default encryption enabled on all buckets. TLS 1.2+ enforced on ALBs.', findings: [], evidence_ids: ['ev_demo_4', 'ev_demo_10'], recommendations: ['Monitor encryption compliance.', 'Implement data classification policies.', 'Regular encryption key rotation.'], auditor_questions: ['How is data encryption enforced?', 'What encryption standards are used?', 'Describe data movement controls.', 'Show evidence of encryption key management.'], analyzed_at: completed },
      { control_id: 'CC7.1', name: 'Configuration & Vulnerability Management', status: 'pass', gap_score: 84, freshness_score: 100, summary: 'AWS Config tracking 142 resources. SecurityHub CIS standard at 86% pass rate.', findings: [], evidence_ids: ['ev_demo_6'], recommendations: ['Expand Config coverage to all regions.', 'Implement automated remediation.', 'Regular vulnerability scanning.'], auditor_questions: ['What configuration management tools are used?', 'How are vulnerabilities tracked and remediated?', 'Describe change management for configurations.', 'Show evidence of configuration compliance.'], analyzed_at: completed },
      { control_id: 'CC7.2', name: 'Security Event Monitoring', status: 'pass', gap_score: 86, freshness_score: 100, summary: 'CloudTrail multi-region trail with management + data events; CloudWatch metric filters and alarms in place.', findings: [], evidence_ids: ['ev_demo_9', 'ev_demo_25'], recommendations: ['Enable data event logging for S3.', 'Implement centralized logging.', 'Set up automated alerting.'], auditor_questions: ['What security events are monitored?', 'How are logs collected and analyzed?', 'Describe incident detection capabilities.', 'Show examples of security monitoring.'], analyzed_at: completed },
      { control_id: 'CC7.3', name: 'Anomaly Detection', status: 'partial', gap_score: 72, freshness_score: 100, summary: 'CloudWatch alarms cover billing + EC2 health; GuardDuty enabled in 5 of 6 regions. SNS notifications routed to PagerDuty.', findings: [], evidence_ids: ['ev_demo_2', 'ev_demo_3', 'ev_demo_15', 'ev_demo_16'], recommendations: ['Add GuardDuty in eu-west-1.', 'Implement machine learning-based anomaly detection.', 'Expand monitoring coverage.'], auditor_questions: ['What anomalies are detected?', 'How are anomalies investigated?', 'Describe threat detection capabilities.', 'Show evidence of anomaly response.'], analyzed_at: completed },
      { control_id: 'CC7.4', name: 'Incident Response', status: 'fail', gap_score: 48, freshness_score: 100, summary: 'GuardDuty disabled in eu-west-1; SecurityHub reports 7 active HIGH findings older than 30 days.', findings: [{ id: 'f3', severity: 'HIGH', title: 'GuardDuty disabled in eu-west-1', description: 'No detector in active region with workloads.', evidence_id: 'ev_demo_3', remediation: 'aws guardduty create-detector --enable' }, { id: 'f6', severity: 'HIGH', title: '7 active HIGH SecurityHub findings', description: 'Findings older than 30 days indicate inadequate incident response.', evidence_id: 'ev_demo_8', remediation: 'aws securityhub batch-update-findings --finding-identifiers Id=arn:aws:securityhub:us-east-1:743820195634:subscription/cis-aws-foundations-benchmark/v/1.2.0/1.5/finding/123 --note-text "Resolved" --workflow Status=RESOLVED' }], evidence_ids: ['ev_demo_3', 'ev_demo_8'], recommendations: ['Enable GuardDuty everywhere; ingest findings to SIEM.', 'Implement automated finding remediation.', 'Develop incident response playbooks.', 'Set up 24/7 monitoring.'], auditor_questions: ['Describe the incident response process.', 'How are security findings triaged?', 'What tools support incident response?', 'Show evidence of incident handling.'], analyzed_at: completed },
      { control_id: 'CC8.1', name: 'Change Management', status: 'pass', gap_score: 82, freshness_score: 100, summary: 'CloudTrail captures 100% of change events; Config records resource history; Lambda functions tagged with version + commit SHA.', findings: [], evidence_ids: ['ev_demo_9', 'ev_demo_13', 'ev_demo_22'], recommendations: ['Implement change approval workflows.', 'Automate change tracking.', 'Regular change audits.'], auditor_questions: ['How are changes managed and approved?', 'What change tracking exists?', 'Describe deployment processes.', 'Show evidence of change controls.'], analyzed_at: completed },
      { control_id: 'CC9.2', name: 'Business Continuity & Recovery — AWS Layer Only', status: 'fail', gap_score: 38, freshness_score: 100, audit_risk: 'CRITICAL', summary: 'Recovery procedures and BCDR governance are outside AWS API assessment scope. Within the technical layer: acmepay-prod-billing RDS has 0-day backup retention and is single-AZ. Other instances are configured correctly.', findings: [{ id: 'f4', severity: 'CRITICAL', title: 'Production RDS without backups', description: 'acmepay-prod-billing — BackupRetentionPeriod=0, MultiAZ=false. Data loss on instance failure would be unrecoverable beyond the most recent transaction log flush.', evidence_id: 'ev_demo_4', remediation: 'aws rds modify-db-instance --db-instance-identifier acmepay-prod-billing --backup-retention-period 7 --multi-az --apply-immediately' }], evidence_ids: ['ev_demo_4', 'ev_demo_20'], recommendations: ['Set BackupRetentionPeriod ≥ 7 days for all production RDS.', 'Enable MultiAZ on acmepay-prod-billing.', 'Document RPO/RTO targets and provide them to your auditor — the API cannot verify these.', 'Implement automated backup testing.'], auditor_questions: ['What is your documented RPO and RTO for acmepay-prod-billing?', 'When was the last successful restore-from-backup test, and where is the runbook?', 'How are backups validated?', 'Describe disaster recovery capabilities.'], partially_assessable: true, disclaimers: ['Recovery procedures and testing outside technical scope. RTO/RPO targets and tabletop exercises must be evaluated by your auditor separately.'], analyzed_at: completed },
    ],
  };
  return {
    id: 'demo_acmepay',
    org_name: 'AcmePay, Inc.',
    results,
    created_at: created,
    completed_at: completed,
    evidence_count: 847,
  };
}
